from attractor.registry import DEFAULT_HF_ORG


configs = [
    dict(
        name="attractor-xlarge-1_3b",
        hf_config=dict(org=DEFAULT_HF_ORG, name="attractor-xlarge-1_3b"),
        block_size=2048,
        vocab_size=32768,
        padding_multiple=64,
        n_embd=1536,
        num_attention_heads=12,
        num_key_value_heads=12,
        intermediate_size=6144,
        bias=False,
        tie_embeddings=True,
        architecture_class_name="Attractor",
        block_class_name="TransformerPreNormBlock",
        norm_class_name="RMSNorm",
        norm_eps=1e-5,
        mlp_class_name="BaseMLP",
        nonlin_name="ReLU2",
        qk_norm=True,
        logit_softcap=None,
        n_backbone_layers=23,
        n_fp_blocks=3,
        solver="anderson",
        max_iter=64,
        min_iter=8,
        tol=1e-4,
        anderson_m=5,
        anderson_beta=1.0,
        backward_type="onestep",
        backward_max_iter=64,
        backward_min_iter=8,
        backward_tol=1e-4,
        adjoint_grad_clip=None,
        layer_scale_init=0.5,
        gamma_max=1.0,
        fp_lr_scale=0.75,
        init_strategy="scaled-zero",
        init_orthogonal=True,
    ),
]
