from attractor.registry import DEFAULT_HF_ORG


configs = [
    dict(
        name="attractor-large-770m",
        hf_config=dict(org=DEFAULT_HF_ORG, name="attractor-large-770m"),
        block_size=2048,
        vocab_size=32768,
        padding_multiple=64,
        n_embd=1280,
        num_attention_heads=10,
        num_key_value_heads=10,
        intermediate_size=5120,
        bias=False,
        tie_embeddings=True,
        architecture_class_name="Attractor",
        block_class_name="TransformerPreNormBlock",
        norm_class_name="RMSNorm",
        norm_eps=1e-5,
        mlp_class_name="BaseMLP",
        nonlin_name="ReLU2",
        qk_norm=True,
        logit_softcap=None,
        n_backbone_layers=35,
        n_fp_blocks=2,
        solver="anderson",
        max_iter=32,
        min_iter=6,
        tol=1.5e-4,
        anderson_m=5,
        anderson_beta=0.96,
        backward_type="anderson",
        backward_max_iter=32,
        backward_min_iter=6,
        backward_tol=1.5e-4,
        adjoint_grad_clip=2.0,
        layer_scale_init=0.73,
        gamma_max=0.9,
        fp_lr_scale=0.4,
        fp_wd=0.1,
        init_strategy="scaled-zero",
        init_orthogonal=True,
    ),
]
